[package]
name = "bloom-relay-dns"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bloom-relay-protocol.workspace = true
thiserror.workspace = true
tokio.workspace = true
aws-sdk-route53.workspace = true
hickory-resolver.workspace = true
